version: 0.1

local-dev:
  deploy:
    parameters:
      stack_name: serverless-ticketing-notifications-local-dev
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      fail_on_empty_changeset: false
      resolve_s3: false
      parameter_overrides: ApiStageName=dev
  delete:
    parameters:
      stack_name: serverless-ticketing-notifications-local-dev
      region: sa-east-1
      no_prompts: true

local-prod:
  deploy:
    parameters:
      stack_name: serverless-ticketing-notifications-local-prod
      capabilities: CAPABILITY_IAM
      confirm_changeset: false
      fail_on_empty_changeset: false
      resolve_s3: false
      parameter_overrides: ApiStageName=prod
  delete:
    parameters:
      stack_name: serverless-ticketing-notifications-local-prod
      region: sa-east-1
      no_prompts: true

dev:
  deploy:
    parameters:
      stack_name: serverless-ticketing-notifications-dev
      region: sa-east-1
      capabilities: CAPABILITY_IAM
      confirm_changeset: true
      fail_on_empty_changeset: false
      resolve_s3: true
      parameter_overrides: ApiStageName=dev
  delete:
    parameters:
      stack_name: serverless-ticketing-notifications-dev
      region: sa-east-1
      no_prompts: true

prod:
  deploy:
    parameters:
      stack_name: serverless-ticketing-notifications-prod
      region: sa-east-1
      capabilities: CAPABILITY_IAM
      confirm_changeset: true
      fail_on_empty_changeset: false
      resolve_s3: true
      parameter_overrides: ApiStageName=prod
  delete:
    parameters:
      stack_name: serverless-ticketing-notifications-prod
      region: sa-east-1
      no_prompts: false
