AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Serverless ticketing notifications API

Parameters:
  ApiStageName:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: API Gateway stage name

Globals:
  Function:
    Runtime: python3.14
    Timeout: 10
    MemorySize: 128

Resources:
  TicketingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref ApiStageName

  AdminApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: serverless_ticketing_notifications.ticketing.infrastructure.api.admin.handler.lambda_handler
      Events:
        ListAdminEventsRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /admin/events
            Method: GET

        CreateAdminEventRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /admin/events
            Method: POST

        GetAdminEventRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /admin/events/{event_id}
            Method: GET

        UpdateAdminEventRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /admin/events/{event_id}
            Method: PATCH

        DeleteAdminEventRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /admin/events/{event_id}
            Method: DELETE
  
  CustomerApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: serverless_ticketing_notifications.ticketing.infrastructure.api.customer.handler.lambda_handler
      Events:
        ListEventsRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /events
            Method: GET
        
        GetEventTicketsRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /events/{event_id}/tickets
            Method: GET

        CreateEventReservationRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /events/{event_id}/reservations
            Method: POST

        CreateReservationCheckoutRoute:
          Type: Api
          Properties:
            RestApiId: !Ref TicketingApi
            Path: /reservations/{reservation_id}/checkout
            Method: POST

Outputs:
  ApiId:
    Description: Ticketing API Gateway id
    Value: !Ref TicketingApi

  ApiStage:
    Description: Ticketing API Gateway stage
    Value: !Ref ApiStageName

  ApiUrl:
    Description: Ticketing API Gateway base URL
    Value: !Sub "https://${TicketingApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}"
