from typing import Protocol

from ticketstream.ticketing.domain.entities.event import Event


class EventRepositoryInterface(Protocol):
    def save(self, event: Event) -> Event: ...
    def update(self, event: Event) -> Event: ...
    def delete(self, event: Event) -> Event: ...
    def findById(self, event_id: str) -> Event: ...
