from typing import Protocol

from ticketstream.ticketing.domain.entities.reservation import Reservation


class ReservationRepositoryInterface(Protocol):
    def create(self, reservation: Reservation) -> Reservation: ...
    def update(self, reservation: Reservation) -> Reservation: ...
    def findById(self, reservation_id: str) -> Reservation: ...
    def findByCategoryId(self, category_id: str) -> list[Reservation]: ...
    def findByUserId(self, user_id: str) -> list[Reservation]: ...
