from typing import Protocol

from ticketstream.ticketing.domain.entities.ticket_category import TicketCategory


class TicketCategoryRepositoryInterface(Protocol):
    def save(self, ticket_category: TicketCategory) -> TicketCategory: ...
    def update(self, ticket_category: TicketCategory) -> TicketCategory: ...
    def delete(self, ticket_category: TicketCategory) -> TicketCategory: ...
    def findById(self, ticket_category: TicketCategory) -> TicketCategory: ...
    def findByEventId(self, event_id: str) -> list[TicketCategory]: ...
