from typing import Protocol

from serverless_ticketing_notifications.ticketing.domain.entity.event import Event


class EventRepository(Protocol):
    def save(self, event: Event) -> None: ...
    def delete(self, event: Event) -> None: ...
    def find_all(self) -> tuple[Event, ...]: ...
    def find_by_id(self, event_id: int) -> Event: ...
