from typing import Protocol

from serverless_ticketing_notifications.ticketing.domain.entity.reservation import (
    Reservation,
)


class ReservationRepository(Protocol):
    def save(self, reservation: Reservation) -> None: ...
    def delete(self, reservation: Reservation) -> None: ...
    def find_all(self) -> tuple[Reservation, ...]: ...
    def find_by_id(self, reservation_id: str) -> Reservation: ...
    def find_by_event_and_user(
        self, event_id: str, user_id: str
    ) -> tuple[Reservation, ...]: ...
