from typing import Protocol

from serverless_ticketing_notifications.ticketing.domain.entity.ticket_tier import (
    TicketTier,
)


class TicketTierRepository(Protocol):
    def save(self, ticket_tier: TicketTier) -> None: ...
    def delete(self, ticket_tier: TicketTier) -> None: ...
    def find_all(self) -> tuple[TicketTier, ...]: ...
    def find_by_id(self, ticket_tier_id: int) -> TicketTier: ...
    def find_by_event_and_category(
        self, event_id: str, category: str
    ) -> tuple[TicketTier, ...]: ...
