from typing import Protocol
from uuid import UUID

from ticketstream.ticketing.domain.entities.reservation import Reservation


class ReservationRepositoryPort(Protocol):
    def create(self, reservation: Reservation) -> Reservation: ...
    def update(self, reservation: Reservation) -> Reservation: ...
    def find_by_id(self, reservation_id: UUID) -> Reservation | None: ...
    def find_by_category_id(self, category_id: UUID) -> list[Reservation]: ...
    def find_by_user_id(self, user_id: UUID) -> list[Reservation]: ...
